version: '3'
services:

  db:
    image: mysql:8.0
    user: "1000:1000"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./rails/src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails/src:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
