version: '3'
services:

  db:
    image: mysql:8.0
    user: "1000:1000"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./rails/src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails/src:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - SPA_ORIGIN=http://localhost:3001
      - JWT_SECRET_KEY=my_secret_key
    depends_on:
      - db

  app:
    build: ./nuxt
    #command: yarn dev -p 3001
    volumes:
      - ./nuxt/src:/nuxt:cached
    #working_dir: "/nuxt/src"
    ports:
      - "3001:3001"
      - "24678:24678"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - VITE_API_ORIGIN=http://localhost:3000
