# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.1.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  rails-build:
    docker:
      - image: cimg/ruby:2.7.6-browsers
    working_directory: ~/media/rails-app-shogi/rails/src
    steps:
      - checkout:
          path: ~/media #一階層しか無理っぽい。~/media/rails-app-shogiとかできない
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

  rails-test:
    docker:
      - image: cimg/ruby:2.7.6-browsers
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/media/rails-app-shogi/rails/src
    steps:
      - checkout:
          path: ~/media
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: webpacker compile
          command: bundle exec rails webpacker:compile
      - run:
          name: test
          command: bundle exec rspec

  nuxt-build:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: test
      CHOKIDAR_USEPOLLING: true
    working_directory: ~/media/rails-app-shogi/nuxt/src
    steps:
      - checkout:
          path: ~/media
      - run:
          name: nuxt/install-deps
          command: yarn install

  nuxt-test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/media/rails-app-shogi/nuxt/src
    steps:
      - checkout:
          path: ~/media
      - run:
          name: nuxt/install-deps
          command: yarn install
      - run:
          name: nuxt test
          command: yarn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - rails-build
      - rails-test:
          requires:
            - rails-build

      - nuxt-build
      - nuxt-test:
          requires:
            - nuxt-build
